services:
  db:
    image: postgres:16
    container_name: owl-db
    environment:
      POSTGRES_DB: confhub
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # для подключения из DBeaver/pgAdmin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d confhub"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ./backend/conf-hub-backend
      dockerfile: confhub-core/ConfHub.Core.Web/Dockerfile
    container_name: owl-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=confhub;Username=app;Password=password
      - JWT__ISSUER=ConfHub
      - JWT__AUDIENCE=ConfHubUsers
      - JWT__KEY=your-super-long-secret-key-must-be-at-least-32-characters-long
    expose:
      - "8080"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: nginx:alpine
    container_name: owl-frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api

volumes:
  postgres_data: