version: '3.4'
services:
  postgres-data:
    image: postgres:latest
    command: ["postgres", "-c", "max_connections=2000"]
    environment:
      POSTGRES_DB: ConfHubData
      POSTGRES_USER: ConfHubAdmin
      POSTGRES_PASSWORD: ConfHubAdmPass
    ports:
      - "1212:5432"
    networks:
      - ConfHubNet
  
  minio:
    image: minio/minio:latest
    environment:
      MINIO_ACCESS_KEY: "confHubMinIOaccess"
      MINIO_SECRET_KEY: "confHubMinIOsecret"
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - minio-data:/data
    networks:
      - ConfHubNet

  sibadi-conf-hub:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    container_name: confhub-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-data:5432/ConfHubData
      SPRING_DATASOURCE_USERNAME: ConfHubAdmin
      SPRING_DATASOURCE_PASSWORD: ConfHubAdmPass
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: confHubMinIOaccess
      MINIO_SECRET_KEY: confHubMinIOsecret
      MINIO_BUCKET: confhub-files
    depends_on:
      - postgres-data
      - minio
    networks:
      - ConfHubNet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: confhub-frontend
    ports:
      - "3000:80"
    depends_on:
      - sibadi-conf-hub
    networks:
      - ConfHubNet

networks:
  ConfHubNet:
    driver: bridge

volumes:
  minio-data:
    driver: local